### ISSUE TITLE
NGlycan: missing ring information

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#41]
Missing ring information should be treated the same way as missing anomer or linkages (see #39):

G00328HB
![1](https://image.glycosmos.org/snfg/png/G00328HB)

**Comment by edwardsnj** [comment]
Ring information is already treated in the same way as missing anomers - if specified in the motif, it must be matched. We have already modified our primary glycan core motifs to remove ring information at the reducing end (where ring information is typically missing). In this case, the missing ring information is not at the reducing end, but instead in the first Man residue, so it is not matched. One solution for #39 (and here) is to remove all ring-information (and anomer and linkage) from the motif structures, rather than using subsumption. Will have to think about the implications.

**Comment by ReneRanzinger** [comment]
See [comment ](https://github.com/glygen-glycan-data/PyGly/issues/39#issuecomment-728739731) on the other ticket. Removing the information in the motif will lead to false positives. Better to handle this in a specific alignment algorithm. Or subsumption might work as well. But that would only work if this structure has a leaf that matches the motif. If the structure itself is the leaf how would subsumption work?

**Comment by edwardsnj** [comment]
In the new motif alignment implementation, non-strict alignments will match even if ring information is missing.

See: https://edwardslab.bmcb.georgetown.edu/glycandatadev/G00328HB#Classification

**Comment by ReneRanzinger** [comment]
@edwardsnj For this kind of problem it would be nice to have a page with the delta that was generated by applying this new rule. Or a comma separated list of GlyTouCan IDs. Otherwise we can close this ticket.

**Comment by edwardsnj** [comment]
See this site for a list of added or removed subtypes, including N-glycan subtypes, in the next release:

   http://edwardslab.bmcb.georgetown.edu/~nedwards/dropbox/5SCrtrAXjf/
