### ISSUE TITLE
Classification of G03246MZ

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#48]
G03246MZ
![1](https://image.glycosmos.org/snfg/png/G03246MZ)

Should be classified as N-Glycan. Might be hard to get the subclassification as complex be correct.

**Comment by edwardsnj** [comment]
Thanks to Wenjin's hard work on structures with repeats, we should be able to support the classification of this glycan as N-glycan in the next GlycanData release. Unfortunately, this will not match the N-glycan complex motif, not because of the repeating section, but because of the carbon bond position 3 at the top mannose, which is not compatible with the 2|4 linkage expected.

**Comment by ReneRanzinger** [comment]
That sounds good. Yeah I missed the linkage 3 problem.

**Comment by edwardsnj** [comment]
GlycoMotif now supports alignments against structures with repeating elements. This glycan has been classified as N-glycan in GlyGen-GlycanData-Export-v1.10.0. Note the apparently this matches the N-glycan complex motif, which I don't think it should, so I'm leaving this open until I understand why this is happening.

**Comment by edwardsnj** [comment]
I have checked the glycan sequences (both WURCS and GlycoCT) and believe that the sequences indicate a 2-position linkage entering the repeating unit, note the 3 as shown. If a 2, then the motif match of the complex N-linked glycan core is correct, and this is not an error. I have submitted an issue to the GlycanBuilder2 repository to reflect the incorrectly drawn image. https://github.com/glycoinfo/GlycanBuilder2/issues/57
